apiVersion: v1
kind: Pod
metadata:
  name: nodeport-pod
  labels:
    name: nodeport-lable
    app: nginx
spec:
  containers:
  - name: nodeport-container
    image: nginx
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    name: labnodeport-lablele
    app: nginx
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 #container port
