apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  namespace: roboshop
spec:
  containers:
  - name: hello-pod
    image: nginx
    ports:
    - containerPort: 80

# apiVersion: v1
# kind: Pod
# metadata:
#   name: mypod
#   namespace: test
#   labels:
#     name: mypod
# spec:
#   containers:
#   - name: mypod
#     image: nginx

# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx
# spec:
#   containers:
#   - name: nginx
#     image: nginx:1.14.2
#     ports:
#     - containerPort: 80
