apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  namespace: hello-pod
spec:
  containers:
  - name: web-nginx
    image: nginx
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: multi-pod1
  namespace: hello-pod
spec:
  containers:
  - name: web-nginx1
    image: nginx
    ports:
    - containerPort: 80

---
apiVersion: v2
kind: Pod
metadata:
  name: multi-pod2
  namespace: hello-pod
spec:
  containers:
  - name: web-nginx2
    image: nginx
    ports:
    - containerPort: 80
