apiVersion: v1
kind: Pod
metadata:
  name: multi-container1
spec:
  containers:
  - name: web-nginx2
    image: nginx
    ports:
    - containerPort: 80
  - name: almalinux
    image: almalinux:8
    ports:
    command: ["sleep", "300"]