apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec:
  containers:
  - name: web-nginx2
    image: nginx
    ports:
    - containerPort: 80
  - name: web-nginx3
    image: nginx
    ports:
    - containerPort: 80