apiVersion: v1
kind: Pod
metadata:
  name: annotation-demo
  labels:
    proj: devops
    env: qa
  annotations:
    jenkis-url: "http://roboshop.devopslife.cloud"
spec:
  containers:
  - name: web-nginx
    image: nginx
    ports:
    - containerPort: 80