apiVersion: v1
kind: Pod
metadata:
  name: nginx-resource
spec:
  containers:
  - name: nginx-app
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  