apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  # list of containers
  containers:
  - name: config-container
    image: nginx
    #here with this line port will not be opened, just for information
    ports:
    - containerPort: 80
    env:
    - name: course
      valueFrom:
        configMapKeyRef:
          name: devops-config # The ConfigMap this value comes from.
          key: course
    - name: leaners
      valueFrom:
        configMapKeyRef:
          name: devops-config
          key: leaner
---
apiVersion: v1
kind: Pod
metadata:
  name: config-pod1
spec:
  # list of containers
  containers:
  - name: config-container1
    image: nginx
    #here with this line port will not be opened, just for information
    ports:
    - containerPort: 80
    envFrom:
      - configMapRef:
          name: devops-config