apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  # list of containers
  containers:
  - name: config-container
    image: nginx
    #here with this line port will not be opened, just for information
    ports:
    - containerPort: 80
    env:
    - name: course
      valuefrom:
        configMapKeyRef:
          name: devops-config # The ConfigMap this value comes from.
          key: course
    - name: leaners
      valuefrom:
        configMapKeyRef:
          name: devops-config
          key: leaner
