apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  # list of containers
  containers:
  - name: secret-container
    image: nginx
    #here with this line port will not be opened, just for information
    ports:
    - containerPort: 80
    envFrom:
      - secretKeyRef:
          name: secret-values