apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    env: sandbox
spec:
  replicas: 3
  selector:
    matchLabels:
      env: sandbox
  template:
    metadata:
      labels:
        env: sandbox
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-service
#   labels:
#     env: sandbox
# spec:
#   type: NodePort
#   ports:
#   - port: 80
#   selector:
#     env: sandbox

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    env: sandbox
spec:
  type: NodePort
  ports:
    - port: 443
      nodePort: 32001
      # name: https
  selector:
    env: sandbox